- id: Aid_13_14_001
  alias: Notify telegram when started
  initial_state: 'on'
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      entity_id: switch.noderedctl
    service: switch.turn_on
  - data:
      entity_id: switch.zncctl
    service: switch.turn_on
  - data:
      entity_id: switch.flux
    service: switch.turn_on
  - data:
     message: HA started
    service: notify.telegram_notif_bot
- id: Aid_xx_14_001
  alias: Notify telegram zone change
  trigger:
  - entity_id: device_tracker.frederic_g4
    platform: state
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - data_template:
      message: 'leaving {{ trigger.from_state.state }} and entering {{ trigger.to_state.state
        }} '
    service: notify.telegram_notif_bot
- id: Aid_01_04_001
  alias: Eteind la lumiere dans la cuisine si absent.
  trigger:
  - platform: state
    entity_id: device_tracker.frederic_g4
    to: away
  action:
    service: light.turn_off
    entity_id: light.plafond
- id: Aid_01_06_001
  alias: Turn on lampe_chevet in night mode
  trigger:
    platform: state
    entity_id: sensor.ecran_g4
    to: '1'
  condition:
    condition: time
    after: 00:00:00
    before: 06:30:00
  action:
    service: scene.turn_on
    entity_id: scene.lumiere_nuit
- id: Aid_13_13_001
  alias: Sonarr info  visibility
  trigger:
  - platform: state
    entity_id: switch.radarrctl
    to: 'on'
  - platform: event
    event_type: homeassistant_start
  action:
    service: script.group_visibility
    data:
      entity_id: group.radarr_group
      cond: switch.radarrctl
      visible_state: 'on'
- id: Aid_13_13_002
  alias: Radarr info visibility
  trigger:
  - platform: state
    entity_id: switch.sonarrctl
    to: 'on'
  - platform: event
    event_type: homeassistant_start
  action:
    service: script.group_visibility
    data:
      entity_id: group.sonarr_group
      cond: switch.sonarrctl
      visible_state: 'on'
- id: Aid_13_13_003
  alias: Associate Chambre Light list box with scene
  trigger:
    platform: state
    entity_id: input_select.light_chamber_preset
  action:
    service: scene.turn_on
    data_template:
      entity_id: "{% if is_state(\"input_select.light_chamber_preset\", \"lecture\"\
        ) %}\n   scene.lecture\n{%-elif is_state(\"input_select.light_chamber_preset\"\
        , \"nuit\") %} \n   scene.nuit\n{% else %}\n   none\n{% endif %}\n"
- action:
  - data:
      parse_mode: markdown
      inline_keyboard:
      - /Yes
      - /No
      message: Confirm reboot
    service: telegram_bot.send_message
  alias: Confirm reboot when receiving telegram command /reboot
  condition: []
  id: '1505022137314'
  trigger:
  - event_data:
      command: /reboot
    event_type: telegram_command
    platform: event
- action:
    service: shell_command.reboot_cmd
  alias: Reboot when callback called
  condition:
    condition: template
    value_template: '{{ trigger.event.data.message.text == "Confirm reboot"}}'
  id: '1505027664992'
  trigger:
  - event_type: telegram_callback
    platform: event
    event_data:
      data: /Yes
