- id: Aid_13_14_001
  alias: Notify telegram when started
  initial_state: 'on'
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      entity_id: switch.noderedctl
    service: switch.turn_on
  - data:
      entity_id: switch.zncctl
    service: switch.turn_on
  - data:
      entity_id: switch.flux
    service: switch.turn_on
  - data:
     message: HA started
    service: notify.telegram_notif_bot
- id: Aid_xx_14_001
  alias: Notify telegram zone change
  trigger:
  - entity_id: device_tracker.frederic_g4
    platform: state
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - data_template:
      message: 'leaving {{ trigger.from_state.state }} and entering {{ trigger.to_state.state
        }} '
    service: notify.telegram_notif_bot
- id: Aid_01_04_001
  alias: Eteind la lumiere dans la cuisine si absent.
  trigger:
  - platform: state
    entity_id: device_tracker.frederic_g4
    to: away
  action:
    service: light.turn_off
    entity_id: light.plafond
